/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UpdateUserImport } from './routes/update-user'
import { Route as RegistrationImport } from './routes/registration'

// Create/Update Routes

const UpdateUserRoute = UpdateUserImport.update({
  id: '/update-user',
  path: '/update-user',
  getParentRoute: () => rootRoute,
} as any)

const RegistrationRoute = RegistrationImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationImport
      parentRoute: typeof rootRoute
    }
    '/update-user': {
      id: '/update-user'
      path: '/update-user'
      fullPath: '/update-user'
      preLoaderRoute: typeof UpdateUserImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/registration': typeof RegistrationRoute
  '/update-user': typeof UpdateUserRoute
}

export interface FileRoutesByTo {
  '/registration': typeof RegistrationRoute
  '/update-user': typeof UpdateUserRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/registration': typeof RegistrationRoute
  '/update-user': typeof UpdateUserRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/registration' | '/update-user'
  fileRoutesByTo: FileRoutesByTo
  to: '/registration' | '/update-user'
  id: '__root__' | '/registration' | '/update-user'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  RegistrationRoute: typeof RegistrationRoute
  UpdateUserRoute: typeof UpdateUserRoute
}

const rootRouteChildren: RootRouteChildren = {
  RegistrationRoute: RegistrationRoute,
  UpdateUserRoute: UpdateUserRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.ts",
      "children": [
        "/registration",
        "/update-user"
      ]
    },
    "/registration": {
      "filePath": "registration.tsx"
    },
    "/update-user": {
      "filePath": "update-user.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
